### ISSUE TITLE
Possible Visual Cue for Grab book and Grab zoomed-in book

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#141]
In #126, @zepumph mentioned a visual cue for grabbing the book and zoomed-in book similar to BASE.

Copied key icons from BASE's design

Here's a rough draft of what the two-step grab and move visual cuing could look like for Friction. We could possibly play with the size of the key icons to cue the more important actions.

**1. When a user moves keyboard focus to Chemistry book:**
- Mouse Left-Right Arrows disappear
- Pink focus with Grab hint appear around Chemistry Book
<img width="829" alt="01-chem-book-focus-hint-no-arrows" src="https://user-images.githubusercontent.com/1902116/47650385-5ef1c580-db80-11e8-9d00-a29a05d8c422.png">

**2. Keyboard focus moves to Zoomed-in book:**
- Mouse Left-Right Arrows disappear (remain hidden)
- Pink focus with Grab hint appear around Zoomed-in book
![small-01-zoomed-in-focus-hint-no-arrows](https://user-images.githubusercontent.com/1902116/47650974-2bb03600-db82-11e8-9461-64dbbaf1a8dc.png)

**3. User activates grab on Chemistry book:**
- Mouse Left-Right Arrows disappear (remain hidden)
- Pink focus changes to a dashed line
- Move keys appear around highlighted book
![small-02-move-book-hint-all-letters-big](https://user-images.githubusercontent.com/1902116/47651123-995c6200-db82-11e8-9d8b-49b180a4cc5d.png)

**4. User activates grab on Zoomed-in book:**
- Mouse Left-Right Arrows disappear (remain hidden)
- Pink focus changes to a dashed line
- Move keys appear around highlighted Zoomed-in book
![small-02-move-zoomed-in-book-hint-all-letters-big](https://user-images.githubusercontent.com/1902116/47651176-c3158900-db82-11e8-860d-bcb29d477581.png)

**Comment by terracoda** [comment]
In addition I played with the size of the letter icons to see if it might be useful to cue the A,D, and S keys more than W key.

Here are a few options:
**W key smaller on Chemistry book**
![small-02-move-book-hint-w-smaller](https://user-images.githubusercontent.com/1902116/47651321-2a333d80-db83-11e8-97d5-395c43584a85.png)

**W key smaller on Zoomed-in book**
![small-02-move-zoomed-in-book-hint-w-smaller](https://user-images.githubusercontent.com/1902116/47651389-5222a100-db83-11e8-9fbc-d00d1a6c6b97.png)

**W and S keys smaller on Zoomed-in book**
![small-02-move-zoomed-in-book-hint-w-s-smaller](https://user-images.githubusercontent.com/1902116/47651440-754d5080-db83-11e8-8bd7-bacd22c5414f.png)

**Comment by terracoda** [comment]
Tagging and assigning to @emily-phet and @arouinfar for initial feedback.

**Question:** 
Do you think that something very similar to BASE's grab and move visual cue could work for Friction?

**Comment by emily-phet** [comment]
Thanks for mocking this up! I was just thinking about this. :) 

I think this sim will be a little trickier than BASE when it comes to visual cueing:

- The spacing tighter and coloring is brighter in this sim.

- The books can be in different locations at first pickup (e.g., once one book has been interacted with, the other book can be in any state when a user first gets to it to pick it up).

- The sim already has arrow cues!

I would like to consider some way to have the visual cues central over the book in question, while perhaps making the colors behind slightly transparent or 'dulled' in some way - so that the cue 'pops' more. This would feel like you're in "grab mode" and 'move mode'.

I would also like to consider removing the W, A, S and D visual cues. @terracoda can you remind me why we have these in the visual design? Arrow keys are far more intuitive for most, and the fact that W, A, S and D are options are provided verbally to those accessing description and in the keyboard help verbally and visually. Is there a specific scenario we're trying to address by having W, A, S, and D in the visual cue (that I just can't recall right now)?

**Comment by terracoda** [comment]
@emily-phet, we cue the WASD keys because they actually work better. The arrow keys do not respond as well, though they do seem to work now in all screen readers (need to verify JAWS and Chrome). 

The WASD keys just work better with a screen reader on.

**Comment by terracoda** [comment]
@emily-phet, keep in mind, we only visually cue the initial interaction - hoping that is enough to scaffold users. I would hope that it would not be necessary to provide the cues after successful interaction.

**Comment by emily-phet** [comment]
> The WASD keys just work better with a screen reader on.

@terracoda  - yes, this was my understanding as well. If that's the case, I don't think we need to continue with the goal of including the W, A, S, and D keys in the visual cues. If you're using a screen reader, you'll hear the W, A, S, and D keys emphasized in the verbal cues.

**Comment by terracoda** [comment]
We could definitely try providing the WASD instruction solely for screen reader users in the PDOM, and also in the Keyboard Shortcuts dialog. I think it would be helpful for all user, especially teachers to have access to alternative shortcuts.

**Comment by arouinfar** [comment]
Thanks for all of these mockups @terracoda!

It's not clear to me why we need to require extra key presses to interact with the sim, but I'll assume there are good reasons for it. I know I've been a bit out of the loop on what's been going on in the a11y design for this sim.

In both cases, I think the grab cue looks fine. However, I find the WASD keys to be a bit crowded looking. I'd also prefer to keep the keys the same size so things look uniform, which I realize is somewhat at odds with keeping things from getting too crowded. I like @emily-phet's suggestion to display just the arrows.

For the book itself, maybe we could try brightly colored arrows after it's been grabbed? These arrows are similar in style to the cueing arrows in the zoomed-in view.
![image](https://user-images.githubusercontent.com/8419308/47753281-9afa5880-dc5c-11e8-9635-93155c4207c4.png)

I'm struggling with the zoomed-in view of the book, as it already has large cueing arrows. I would imagine visual keyboard users would instinctively use the left/right arrows. Perhaps after the grab cue is dismissed, the cueing arrows would serve as enough of a hint.
![image](https://user-images.githubusercontent.com/8419308/47752756-fcb9c300-dc5a-11e8-9875-c14e4ddee2fe.png)

**Comment by terracoda** [comment]
@arouinfar, I really like the all pink arrows - I didn't like the white-only approach for this sim, the pink is good.

How about swapping out the white arrows for pink ones (perhaps 4 instead of just 2) when keyboard focus lands on the zoomed-in book? The cues are not needed after successful interaction, so the second grab and move no arrows (neither white nor pink) are provided. 

Reason for all 4 arrows for keyboard users is that left-right movement with arrow keys is much less likely to stray downward as it easily does (often does) with mouse or touch - creating friction, intentionally or unintentionally.

When moving left-right with keyboard the book will not create friction. One must press down arrow to press against the book. Is it important to cue the downward movement for visual keyboard users or let them figure it out as mouse/touch users do?

![img_0585](https://user-images.githubusercontent.com/1902116/47784184-23cccf00-dd05-11e8-9cd9-1ac0fa328fbb.JPG)

**Comment by arouinfar** [comment]
> I really like the all pink arrows

Thanks! I knew magenta would have nice contrast, but I wasn't sure if it'd be <i>too much</i> magenta, since that is the focus color.

> How about swapping out the white arrows for pink ones (perhaps 4 instead of just 2) when keyboard focus lands on the zoomed-in book?

Oh, that makes sense! But perhaps the arrows would be dismissed after a successful grab, rather than focus?

Here are a few iterations on your mockup @terracoda.

1. ![screen shot 2018-10-31 at 12 46 52 pm](https://user-images.githubusercontent.com/8419308/47811333-1e728300-dd0b-11e8-9b5c-c2fef90912d8.png)
2. ![screen shot 2018-10-31 at 12 47 00 pm](https://user-images.githubusercontent.com/8419308/47811335-1e728300-dd0b-11e8-8f69-89ba974fae72.png)
3. ![screen shot 2018-10-31 at 12 48 28 pm](https://user-images.githubusercontent.com/8419308/47811392-4a8e0400-dd0b-11e8-903a-4de7ba918022.png)

I like how (1) and (2) have the arrows anchored in the solid part of the book. (But maybe it's just because the white cueing arrows live there too?) I didn't particularly love the empty space between the four arrows in (1), so I merged them for (2) and (3).

**Comment by terracoda** [comment]
I like 2 best, let's go with that one. 

Of course, I was thinking the white arrows are still there when keyboard is not used as they are there to cue mouse/touch users. The pink arrows only show up once a user presses the grab zoomed-in book button.

I think we can go ahead with this visual. 

@emily-phet any thoughts before assigning for implementation?

**Comment by terracoda** [comment]
@arouinfar, @emily-phet and discussed these visuals a bit more and pondered about just providing three arrows (left, right, and down). This might allow us to keep the same left-right arrows that are currently in the visual design and then just turn them pink and add the down arrow after the grab button is activated by a keyboard user.

So, in both cases the book and the zoomed-in book we would just cue the three important directions. I erased one arrow for the book view and and made some rough arrows for the zoomed-in view. What do you think? Could 3 arrows work?

![3-arrows-book](https://user-images.githubusercontent.com/1902116/47863664-15131480-ddf8-11e8-9527-81a92494be3a.png)

![3-arrows-zoomed-in-book](https://user-images.githubusercontent.com/1902116/47863684-1c3a2280-ddf8-11e8-9b7c-47f7876fbbf9.png)

**Comment by arouinfar** [comment]
That all sounds good to me @terracoda.

Here's what three arrows could look like for the zoomed-in view
![image](https://user-images.githubusercontent.com/8419308/47887891-b2c60e00-de0f-11e8-8059-a8074fc4af20.png)
![image](https://user-images.githubusercontent.com/8419308/47887915-cd988280-de0f-11e8-9e56-c19ed1d29e45.png)

I think the 3-way merged arrow (top) looks a bit strange, so separate arrows may be a better way to go.

**Comment by terracoda** [comment]
I created new issue for implementation, so closing this one.
