### ISSUE TITLE
KeyboardHelpDialog goes out of dev bounds with stringTest=long

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/friction#158]
This was flagged in the RIAW RC in https://github.com/phetsims/resistance-in-a-wire/issues/203 so I thought I would make an issue here before RC shas are grabbed. Assigning to @zepumph  since he is working on this sim.

**Comment by jessegreenberg** [comment]
Also, https://github.com/phetsims/joist/issues/546 was started to see if we can fix this generally, but nothing has come to mind yet.

**Comment by zepumph** [comment]
I agree that it would be nice to have a general solution. on hold until that is figured out.

**Comment by emily-phet** [comment]
@jessegreenberg Is the keyboard help dialog currently translatable? Regardless, if this is an easy RIAW-specific fix, let's do that and consider a general fix in the future.

**Comment by jessegreenberg** [comment]
The visible strings in the keyboard dialog are translatable but the a11y strings in the PDOM are not. I think we have a general fix in https://github.com/phetsims/joist/issues/546 ready to go for Friction!

**Comment by zepumph** [comment]
This has been fixed in https://github.com/phetsims/joist/issues/546. The dialog is looking very good with stringTest long. Closing

**Comment by jbphet** [comment]
Reopening.  I just tested this on [the latest Friction RC](http://localhost:8080/friction/friction_en.html?brand=phet&ea&phetioValidateTandems&stringTest=long&dev), the master version of Friction and the master version of Resistance in a Wire.  It doesn't appear that the issue is fixed.  Here's a screenshot from the Friction RC:

![image](https://user-images.githubusercontent.com/3082831/50797569-7b9e2e00-1292-11e9-904e-0f10628cf435.png)

Here's one from RIAW.  This one isn't as wide, but it's just a little past the dev bounds, which is what @KatieWoe originally reported in https://github.com/phetsims/resistance-in-a-wire/issues/203.

![image](https://user-images.githubusercontent.com/3082831/50797540-60cbb980-1292-11e9-8e86-b4f80cc7c300.png)

This is **not** a problem for the current RC of RIAW since I have a workaround in place there, but should probably be addressed for the current Friction RC.

**Comment by jbphet** [comment]
@KatieWoe just came by and showed me that the reason I was seeing this is because I had a wide browser window.  The keyboard dialog apparently scales with the size of the browser window.  While this strikes me as a little odd, since other dialogs (such as the about dialog) don't do this, it does solve the problem of exceeding dev bounds in the cases where it matters.  @zepumph - if this scaling behavior is known and has been approved by the powers that be, feel free to re-close.

**Comment by zepumph** [comment]
Interesting. I wonder if we need to tweak https://github.com/phetsims/joist/commit/428b7a2d985fd7918e0dbf2c9025d34b724db9db a bit more to get what we need.

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/sun/issues/435 to discuss during dev meeting.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/sun/issues/435 we decided that generally shrinking the Dialog is not something we can do, so we will need to set maxWidth on the help content labels within the dialog to ensure good widths for i18n.

**Comment by zepumph** [comment]
@jessegreenberg what strategy do you think is best in how we set up max widths. I feel like this issue is less of a "mark it work" kinda things, and more like a "let's get HelpContent.js and related files set up to make this as easy as possible for all future sims" kind of thing. I looked at lowering `HelpContent.DEFAULT_TEXT_MAX_WIDTH` and it wasn't obvious to me that this was going to fix much.

**Comment by zepumph** [comment]
@jessegreenberg and I looked into this in a more general way today. We update HelpContent so that its layout was largely based on the label's maxWidth. 

Work I did to test changes (mainly changes are in HelpContent and updating usages):
* fuzz board testing
* open all dialogs with `stringTest=long` (didn't look at xss)
* looked over code 

Next steps: 
* look at uses of maxWidth. I handled this mostly, but we should make sure that there aren't other spots to make this nicer. Also note I added the assertion back in in HelpContent to help catch usages.
* look at usages of HelpContent.DEFAULT_{{SOMETHING}}
* doc HelpContentRow
* MAL goes a bit outside, may want to be tweaked

Over to you @jessegreenberg. Let me know if I can help.

**Comment by jessegreenberg** [comment]
That would make sense, since we are already abbreviating Pg. @arouinfar I think you originally mocked this up, are you OK with abbreviating Pg Down to Pg Dn?

Otherwise, we could allow PageDownKeyNode and maybe PageUpKeyNode to have custom max widths.

**Comment by arouinfar** [comment]
I believe Pg Dn is a pretty standard abbreviation for Page Down, so that'd be fine with me @jessegreenberg.

**Comment by jessegreenberg** [comment]
OK thanks @arouinfar, we will go with that.

**Comment by jessegreenberg** [comment]
I am starting to think that the strategy using HEADING_MAX_WIDTH_SCALAR does a little too much, at least without a way to override it. The dialog in BASE looks like this because the maxWidth is set for the label text.
![image](https://user-images.githubusercontent.com/6396244/51639979-494a2d00-1f30-11e9-83dd-d1dff0d91589.png)

But we want the title to grow longer. I think we should either use an option for headingMaxWidth that overrides using HEADING_MAX_WIDTH_SCALAR or remove HEADING_MAX_WIDTH_SCALAR approach.

**Comment by jessegreenberg** [comment]
When I replace maxWidth: options.baseLabelMaxWidth * HEADING_MAX_WIDTH_SCALAR with 250, all dialogs are still within dev bounds. Generally, the text that makes the dialog go out of bounds is the label text because it has the extra width of the icons. So I am going to remove it because of https://github.com/phetsims/friction/issues/158#issuecomment-456983359. @zepumph are you OK with this?

**Comment by jessegreenberg** [comment]
Sims using HelpContent are no longer setting maxWidth on layout boxes.

**Comment by zepumph** [comment]
Sounds good. Thanks for fine tuning this.

**Comment by jessegreenberg** [comment]
OK sounds good. I started to look into usages of HelpContent.DEFAULT_{{SOMETHING}}. One thing that would help with this is change labelWithIcon and labelWithIconList to take the label string rather than the the Text/RichText. Then clients don't even have to create the Text (nor do they have the ability to do so). Inspecting all usages, there are no cases where fonts other than the default are used.

**Comment by jessegreenberg** [comment]
OK, I think we are at a point where we should take remaining work to scenery-phet. The more work we do here, the more difficult it will be to bring into the release branch. And the rest of this doesn't impact friction (there might be slight differences in layout, but the original issue with the KeyboardHelpDialog has been resolved.)

**Comment by zepumph** [comment]
I feel good about that. My current plan is to cherry pick every commit here over to the branch. Let me know if you think there are any that could be omitted safely (though it doesn't really matter), or if there are some that specifically SHOULDN'T end up in Friction.

**Comment by jessegreenberg** [comment]
OK, sounds good. Master dialog in Friction looks like
![image](https://user-images.githubusercontent.com/6396244/51645577-fb8af000-1f42-11e9-9904-4f110cb9d53e.png)

Once we have commits in the rc branch, Ill continue to make changes in https://github.com/phetsims/scenery-phet/issues/462.

**Comment by zepumph** [comment]
Commit has been cherry-picked into branch (note to self)

**Comment by KatieWoe** [comment]
1.5.0-rc.2 this looks good
