### ISSUE TITLE
The reset sim hint is firing too often. 

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/friction#209]
During the interviews, it seems that this hint response was firing too much so @zepumph and I discussed some possible solutions. 
@zepumph has a couple of ideas to fine-tune it.

**Comment by zepumph** [comment]
I'm not sure how the above will fair with #211, because the reset hint is a hint, and the max temp is a context. I'll have to see.

**Comment by zepumph** [comment]
From design meeting today, and decisions made in https://github.com/phetsims/friction/issues/214, we decided to try making the reset-sim hint response always alert, but to hide it under hints. This works great in voicing! The issue is potetntially in description, if that is too verbose. It doesn't sound that way to me though.

Questions for reviewer:
- how does the voicing sound when all atoms have broken away, and the user is still at max temp. Note that when hints are checked, you will get the reset-sim hint each time the max temp alert occurs.
- How does the description sound? Note that the code is SO MUCH simpler if this design works, but otherwise @jessegreenberg and I can continue to brainstorm ways to deviate voicing and description implementations to match the design.

**Comment by Matthew-Moore240** [comment]
The new version sounds much better. We can stick with how it's implemented now. Closing.
