### ISSUE TITLE
Changes to grabbed hint

### ISSUE THREAD

**Issue by zepumph** [phetsims/friction#231]
From design meeting today.

We don't want to hear "move down to rub harder" on grabbed, only when there is unproductive rubbing.

one option is to always change the hint to always say "rub fast or slow"

the other option is to just get rid of the hint on grab.

Right now we are going to get rid of the grabbed hint alert entirely, and we can get it back if we want it.

**Comment by zepumph** [comment]
Hints removed for grabbed alerts above.

**Comment by zepumph** [comment]
@terracoda, I will get you a dev version soon, then assign you to review.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/friction/1.6.0-dev.14/phet/friction_all_phet.html?voicingInitiallyEnabled

**Comment by terracoda** [comment]
I think it sounds good that no hint on grab.

**When using the keyboard,** 
- I hear the move-down hint after three (or maybe two) unproductive rubs (this seems good)
- I hear the rub-hint as soon as contact with book is made (this seems good)
- I hear the reset-hint after all atoms that can be vaporized are vaporized, and then I keep hearing it quite often, even after I stop rubbing. (I think the timing of the reset-hint needs adjustments.)

**When using a mouse, the experience is quite different. This may be intentional.** 
- I never hear the move-down hint, even when rubbing back and forth several times and I do not bring the books together.
- I never hear the rub-hint when the books come together.
- I don't think I ever hear temp-warmer-jiggling-faster responses. (this might be intentional).
- I hear the important  very-hot-break-away responses (this is good)
- As with keyboard interaction I hear the reset-hint after all atoms that can be vaporized are vaporized, and then I keep hearing it quite often, even after I stop rubbing. (As with keyboard, I think the timing of the reset-hint needs adjustments.)

**Another related issue that I see/hear:**
**When should the Hint button change to "Reset" hint?**
The hint button changes to "Rest sim to make more observations", before all  atoms that can be vaporized are vaporized. This seems a bit weird to me in Voicing because when rubbing you do not get the reset hint until after all atoms except the sticky last row have vaporized.

**My Thoughts on issue this related issue:**
In the Interactive Description design we used a thresh hold lower than 100% and more than 50% - maybe 75%?? to let blind users know it might be a good to do a reset. When you can see the visual display, this threshold seems a little incongruous to me. How do others feel? If it is easy we could have 2 thresh holds, or maybe we could increase the thresh hold for both Voicing and Interactive Description? I can't remember if there was a reason why we did not go with 100%. It might have been an issue with the model since atoms are always present.

**Additionally, I noticed a few strange utterances** due to web speech which I don't think we can address:
- sometimes Alex says "dot Chemistry Book" in the Current Details button, I think he is reading a period - just make sure the is a space after all periods in that dynamic state description.
- Samantha and Alex both say "slight ly" instead of "slightly", but I think we just have to live with that.

**Comment by terracoda** [comment]
@Matthew-Moore240, is it your intention that you don't want to hear the temp-warmer-jiggling-faster responses when using a mouse. If so, make sure that's clear in the design documentation. If not, you'll need to work with @zepumph to get this responses to fire when using the mouse as well as with the keyboard.

**Comment by terracoda** [comment]
I hope this is all helpful feedback.

**Comment by terracoda** [comment]
Assigning to @zepumph and @Matthew-Moore240 to address comments. Please let me know if you want me to join in on your Friday session.

**Comment by terracoda** [comment]
I forgot to mention, when using the mouse, I always get the initial state information on grab, "Atoms jiggle a tiny bit, temperature cool." And I get that response each time I touch the book and do not create any or much friction. I would expect to get the rub-hint, "Rub fast or slow" instead of a repeat of the state.

**Comment by zepumph** [comment]
>I hear the reset-hint after all atoms that can be vaporized are vaporized, and then I keep hearing it quite often, even after I stop rubbing. (I think the timing of the reset-hint needs adjustments.)

If the temp is really really high, then you can get this alert even when there is no interaction, when waiting for the sim to cool down. We think that though the "reset" hint occurs frequently, it is easiest, and fine to just leave it as is, since you can turn it off with the hints checkbox.

**Comment by terracoda** [comment]
Issues #233, #234 and #237 should resolve most of this issue.

**Comment by zepumph** [comment]
Yes @terracoda is right.


> * sometimes Alex says "dot Chemistry Book" in the Current Details button, I think he is reading a period - just make sure the is a space after all periods in that dynamic state description.
> * Samantha and Alex both say "slight ly" instead of "slightly", but I think we just have to live with that.


These will covered by https://github.com/phetsims/friction/issues/237.


We are ready to close this issue.
