### ISSUE TITLE
Mobile VO book pick up instructions given in the middle of two books

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#293]
**Test device**
iPad Air 2
**Operating System**
iPadOS 15.4.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/791
When reading through instructions for the sim with mobile VO, it reads out the "button" for the book, instructions for picking up and dragging the book, then the "button" zoomed in book. It is unclear which book is being referred to in the instructions, when it applies to both. In addition, I found it confusing that the books were referred to as buttons.

**Visuals**
![8538007A-07ED-4795-BE14-2CA74564D379](https://user-images.githubusercontent.com/41024075/161848103-781c5bac-79d1-463f-8695-d791cf64d4fa.png)

**Comment by zepumph** [comment]
We have two thought-through design decisions here. @terracoda could do a better job explaining, but I'll take a first pass:

* The instructions are purposefully in between both books precisely because it applies to both books. Rather than duplicate the info (duplication in general is quite confusing to non visual access), we put it once in a spot where it can be accessed by both spaces. 
* The books are buttons to communicate their interactivity. The "grab drag interaction" that @terracoda has developed is based on having a 2-step interaction to pick up the item (via a button press), and then to be able to use it. I believe that part of the reason for the confusion is that you are on mobile safari, that has some specific behavior (buttons are named "Chemistry Book" instead of "Grab Chemistry Book" and some other changes.


@terracoda does that all sound correct to you?

**Comment by terracoda** [comment]
The related issue about the the regular book is already posted in https://github.com/phetsims/friction/issues/299.

If we fix that, things should be better.

**Comment by terracoda** [comment]
Just an FYI I am using iOS 15.5 now.

**Comment by terracoda** [comment]
I looked in the Friction design document. There are a lot of notes in there about the pros and cons of using `aria-roledescription`. These notes and the interaction and coding issues were worked out in this issue https://github.com/phetsims/friction/issues/152

I think we are using `aria-roledescription` in the Mobile grab-drag interaction whereas we might not be using it for the keyboard interaction on desktop. This difference would account for the removal of "Grab" from the button's name on mobile devices. The `aria-roledescription` indicates the book is movable, and the mobile help text explains how to double tap and and hold to drag the book.

I think the only issue is that the actual grab interaction is not currently working properly.

**Comment by terracoda** [comment]
@KatieWoe, could you explain what you mean by "When reading through instructions for the sim with mobile VO". I think you mean, "When reading through State Descriptions". Am I correct? 

The State Description may contain explicit instructions for custom interactions like the grab-drag buttons in this sim, but generally, the State Descriptions have little to no explicit instructions for how to use an interaction. Blind learners know what to do based on the roles of the interactions (e.g., "button", "slider", "checkbox", etc.)

The "instructions" or "help text" we design should focus on why it would be a good idea to try out the interaction, rather how to activate the interaction.

I hope that helps clarify the approach.

**Comment by terracoda** [comment]
@KatieWoe, does this resolve your question about why the help text is in between the book interactions and why "button" is read out? Do you have any other questions for this issue?
