### ISSUE TITLE
Mobile VO Performance

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/friction#295]
Performance note: on iPad with Mobile VO I was seeing a pretty large lag in the text area wrapper. While VO worked it could take the sim a second or two to catch up to inputs.

**Comment by jessegreenberg** [comment]
I have an iPad Air 2 (I think the oldest generation PhET supports) and VoiceOver with Friction had reasonable performance while I tested for a different issue. There were a couple of big dips in the framerate, but considering the user typically isn't using a graphical display in this situation I think it is good enough for publication.

That being said I am not quite sure what the text area wrapper is, maybe that is a PhET-iO + a11y use case I am not familiar with.

**Comment by zepumph** [comment]
The text area wrapper is already notoriously bad performance, even on powerful machines because of the amount of text from the data stream we are rendering into an HTML textarea. Thanks @jessegreenberg, I think we are ready to close. I just played with friction on my iPad os version 15.6 and it was pretty good. Thanks all!
