### ISSUE TITLE
Screen reader reads "zoomed-in" as "zoomed dash in"

### ISSUE THREAD

**Issue by stemilymill** [phetsims/friction#297]
For https://github.com/phetsims/qa/issues/791.

Win10 Chrome + JAWS

In the overview/description of the sim, JAWS reads "zoomed-in" as "zoomed dash in" every time the zoomed-in view is mentioned.

https://user-images.githubusercontent.com/85511101/162335162-f97793ba-425e-4f74-a191-ffd6d875e35c.mp4

<details><summary>Troubleshooting information: </summary><p>

Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-dev.24/phet/friction_all_phet.html
Version: 1.6.0-dev.24 2022-03-30 15:06:07 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
Language: en-US
Window: 1493x711
Pixel Ratio: 1.125/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</p></details>

**Comment by terracoda** [comment]
The screen reader is reading out the hyphen. I think this is fine as long as the button's label is otherwise correctly formatted. I think the button's label likely looks like this:

`<button>Grab Zoomed-in Chemistry Book</button>`

And that is the correct label.

@stemilymill, screen reader users have the options to adjust the amount of punctuation they hear. Many find an amount they like and get used to hearing it.

I feel the hyphen, in this case, is the correct spelling, so I think we should leave it in.

**Comment by zepumph** [comment]
I agree, @stemilymill I'm going to close this. Let us know if you have any questions and feel free to reopen.
