### ISSUE TITLE
phetioFeatured overrides

### ISSUE THREAD

**Issue by arouinfar** [phetsims/friction#304]
Related to #303 

The PhET-iO design was reviewed in #75 however, this sim still needs `phetioFeatured` overrides before publication, so self-assigning.

**Comment by arouinfar** [comment]
`phetioFeatured` overrides added in the commit above. Everything looks good in master, closing.

**Comment by zepumph** [comment]
I had just one question about this work.

Regarding:

https://github.com/phetsims/friction/blob/186a9079b14cef8a353987962f60443ec201fa3c/js/friction-phet-io-overrides.js#L49-L51

You had to opt out here because in a class called `EnabledProperty` we set phetioFeatured to default to true. Would you like me to set phetioFeatured: false as the default for the grab drag interaction's enabledProperty?

**Comment by zepumph** [comment]
- [ ] Furthermore, are we ready to mark this as phetioDesigned true? I think all has been done with that.

**Comment by arouinfar** [comment]
>  Would you like me to set phetioFeatured: false as the default for the grab drag interaction's enabledProperty?

Yes, that would be great! I unfeatured `grabDragInteraction.enabledProperty` because it is read-only and listens to the `inputEnabledProperty` (which is featured). 

> Furthermore, are we ready to mark this as phetioDesigned true? 

Yes, I think so.
