### ISSUE TITLE
Voicing does not work with Chromebook

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#328]
**Test device**
Chromebook

**Operating System**
 109.0.5414.94

**Browser**
chrome

**Problem description**
For https://github.com/phetsims/qa/issues/886, Voicing doesn't work for Friction using the Chromebook. When I click on things I see the little megaphone appear in the sim tab, but I don't hear anything. 
Voicing only seems to be working in published GFLB and JT (not in published RaP). It didn't work for any of the sims I tried in master (Friction, RaP, GFLB).

Voicing works with mac + chrome and win10 + chrome. 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet/friction_all_phet.html
Version: 1.6.0-rc.1 2023-01-17 16:32:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
I have a chromebook, I can take a look.

**Comment by jessegreenberg** [comment]
I found that if I remove the workaround added in https://github.com/phetsims/gravity-force-lab-basics/issues/303 the problem goes away. The problem from that issue does come back though.

Specifically:
https://github.com/phetsims/utterance-queue/blob/2f64e9580771087750bdc3f1c5ac778abb089f1f/js/SpeechSynthesisAnnouncer.ts#L448-L457

I believe that the times Voicing was working on Chrome 109 were the times I started to use it before the workaround was used.

I was curious why this issue is NOT in published GFL:B, even the workaround references an issue in that sim. But it is explained by this comment: https://github.com/phetsims/gravity-force-lab-basics/issues/303#issuecomment-952408265

I tried putting a string in the workaround like
```js
synth.speak( new SpeechSynthesisUtterance( 'waking' ) );
```

and the problem was fixed. Then, I tried speaking an empty space and the problem still seems fixed. Yuck...

The issue is that speaking an empty string breaks SpeechSynthesis in ChromeOS. I verfied this by changing my HTML test to 
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>TEST PAGE</title>
</head>
<body>
  <button id="button">Speak!</button>
</body>

<script>

  const button = document.getElementById( 'button' );
  button.addEventListener( 'click', event => {
    speechSynthesis.speak( new SpeechSynthesisUtterance( '' ) );
  } );

  window.setInterval( () => {
    console.log( speechSynthesis.speaking );
  } )

</script>
</html>
```

And when I press the button I see
![Screenshot 2023-01-27 4 26 03 PM](https://user-images.githubusercontent.com/6396244/215203756-c31944c9-ed48-4dab-9107-41ee1e7d7222.png)

So that is indeed the problem.

@zepumph can we meet next week to discuss whether we should continue with this workaround (adding a space), possible maintenance releases, or removing this workaround entirely to avoid workaround maintenance pain.

**Comment by jessegreenberg** [comment]
Discussed. We prefer adding a space to the workaround. It seems like the least amount of effort, and lets us keep using the workaround for slow speech synthesis on Chromebooks.

Back to me to add the space. Ill look at which published sims have this problem and use that to inform whether we proceed with a maintenance release.

**Comment by zepumph** [comment]
@jessegreenberg, I'm going to mark this as ready to cherry-pick since the original change for friction has been made, to be verified in RC and/or with you on master. Thanks!

**Comment by jessegreenberg** [comment]
@Nancy-Salpepi can you please verify that this is fixed in master?

**Comment by Nancy-Salpepi** [comment]
Great job! Working just fine in master with Friction (and RaP).

**Comment by jessegreenberg** [comment]
I think that is it for this issue, the only published sim with this problem is RaP (https://github.com/phetsims/ratio-and-proportion/issues/550).

Commit to cherry pick: https://github.com/phetsims/utterance-queue/commit/feff87d79a77545af1ea7219521494a3ce2d123a

**Comment by jessegreenberg** [comment]
`cherry-pick`ed into the friction-1.6 branch of utterance-queue. Ready to verify.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.3. Closing.
