### ISSUE TITLE
With drag input disabled, cue arrows return after reset all

### ISSUE THREAD

**Issue by stemilymill** [phetsims/friction#333]
For https://github.com/phetsims/qa/issues/886

Related to https://github.com/phetsims/scenery-phet/issues/720#issuecomment-1058508950

When  `friction.frictionScreen.view.atomicView.atomDragArea.inputEnabledProperty` is set to false, the cue arrows are hidden. However,  `friction.frictionScreen.view.atomicView.hintArrowsNode.visibleProperty` remains true, and the arrows return after reset all.

**Comment by samreid** [comment]
@matthew-blackman and I collaborated on this issue, and we believe the fix is working correctly.  We tested in studio, trying various combinations of inputEnabledProperty and hint visible property.  All seems well, let's request review from @zepumph , then if it seems OK this can be ready for cherry-picking.

**Comment by zepumph** [comment]
That looks excellent! Thanks. 

I see that toggling the macro book doesn't change the arrows. I think that is right because you can still move the micro view separately. So the arrows are just tied to the micro view.

`friction.frictionScreen.view.topBookNode.inputEnabledProperty`


The functionality works well.

Ready for cherry pick.

**Comment by jessegreenberg** [comment]
Cherry-pick done above, and I confirmed in 1.6 SHAs that if you make `friction.frictionScreen.view.atomicView.hintArrowsNode.visibleProperty` visible: false, the arrows do not return after pressing reset-all.

**Comment by KatieWoe** [comment]
Looks good in rc.3
