### ISSUE TITLE
Voicing doesn't read correct alert with option + R

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/friction#336]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.1

**Browser**
safari/chrome/firefox

**Problem description**
For https://github.com/phetsims/qa/issues/886, if the Chemistry Book has keyboard focus and I use the shortcut `option` + `R` to reset the sim, Voicing doesn't say "Reset All. Everything Reset." Instead it gives information about the Chemistry Book. 

**Steps to reproduce**
1. Enable Voicing and Check all Voicing Options 
2. Tab to either Chemistry book and press `Spacebar`
3. Press `option` + `R`

**Visuals**

https://user-images.githubusercontent.com/87318828/216419873-cf2c4065-0ee3-493d-af2b-2f8b2ae7861d.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Friction‬
URL: https://phet-dev.colorado.edu/html/friction/1.6.0-rc.1/phet/friction_all_phet.html
Version: 1.6.0-rc.1 2023-01-17 16:32:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1600x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment]
This is happening because the change in focus happens after the reset (focus moves from draggable book to grabbable book). The name response from the focus listener cancels the context response of the ResetAllButton.

We have previously assumed that the focus response should be high priority and generally cancel context responses. This is a case where that isn't great. I might check with @terracoda about whether this should be fixed.

**Comment by Nancy-Salpepi** [comment]
With VoiceOver and NVDA, after using the shortcut keys, information about the chemistry book is given and then "Reset All. Everything Reset." is heard.

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi. That makes sense and I could see that happening with the shift in focus described in https://github.com/phetsims/friction/issues/336#issuecomment-1414274749. That behavior is expected and good (and there is also little we can do about it). Ill check with @terracoda today about the expectation for Voicing.

**Comment by jessegreenberg** [comment]
@terracoda and I discussed this and we are OK with this behavior, we want the behavior with focus responses to be consistent even though this particular case is a little odd. The user will hear the Reset All sound, so that indicates successful reset.

@Nancy-Salpepi I am going to go ahead and close, please reopen if you have any concerns.
