### ISSUE TITLE
Check in with Kyle on latest with Friction descriptions

### ISSUE THREAD

**Issue by emily-phet** [phetsims/friction#61]

**Comment by samreid** [comment]
@emily-phet can you please provide more detail for this issue?

**Comment by terracoda** [comment]
@emily-phet, since I am working on the descriptions now, I will go ahead and close this issue.
[Friction: A11y Design Main](https://docs.google.com/document/d/1XXI7SD-ASJwivsBaHgeOZmMcJFFN_s3FU48-syO-G0o/edit#heading=h.uctn2leiizew).

Static description are good, and I am still working on the best approach for a dynamic description, and a few alerts.
