### ISSUE TITLE
Some strings are in friction-strings_en.json and some are in FrictionA11yStrings.js

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#66]
Discovered in https://github.com/phetsims/friction/issues/64

Some a11y strings are in the json:
```json
  "moveBookHeader": {
    "value": "Move Book"
  },
  "moveBook": {
    "value": "Move book"
  },
  "moveInSmallerSteps": {
    "value": "Move in smaller steps"
  }
```
and several are in FrictionA11yStrings.js.

@jessegreenberg should these be consolidated?  Is there a good reason to keep them separate?

**Comment by jessegreenberg** [comment]
The separation is intentional. A11y related strings in the json are visible in the keyboard help dialog, so it is important that they are translatable. Strings in FrictionA11yStrings.js are only available for a screen reader user. In general these strings are not translatable yet because we want to enhance the Rosetta UI by adding context for these strings for translators. We also want some broader community feedback about a11y strings before submitting them for i18n, which we hope to receive as more sims are instrumented with a11y.

Reassigning to @samreid in case there are other questions.

**Comment by samreid** [comment]
That makes sense to me, thanks!
