### ISSUE TITLE
Call FrictionModel.init before the view construction

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#70]
Discovered in #64, FrictionModel has an `init` function which cannot be called until the View has been created, because the view adds elements to the model as the view is created.  This is backwards and would be good to remedy.  This would take somewhere around 2-4 hours to iron out and will impact several parts of the code.  Assigned to @ariel-phet to prioritize/schedule/delegate (a reminder I'm not the "responsible dev" for the sim but happy to work on it if you prefer).

**Comment by jbphet** [comment]
As the responsible dev, I'd be glad to work on it too.

**Comment by ariel-phet** [comment]
@jbphet this would be good to do soon'ish...as this sim is being instrumented for sonification work, I feel like improvements like this can be wrapped up into your sonification days.

**Comment by jbphet** [comment]
At this point, the original "letter of the law" for this issue is met, meaning that all initialization of the model takes place during construction and there is no `FrictionModel.init()` method that is called afterwards.  The main issue was that the individual atoms, of type `Atom`, were being created in the `MagnifierNode`.  It's hard to say why it was done this way originally, but it felt like a gaping architectural flaw, so I've now moved the creation of the atoms to `FrictionModel`.  I've also simplified the tracking of 'evaporated` atoms and I've renamed quite a few things to what I feel will be more understandable names for future maintainers.

There is a bit more that I'd like to do, but I did want to note that the main problem identified by this GitHub issue should now be addressed.

**Comment by jbphet** [comment]
I've now modified `Atom` to have a step function, and the instances are now explicitly stepped by `FrictionModel`. This gets rid of a step emitter that looked to me as though it existed to support the odd relationship between `FrictionModel` and the atoms that were created by `MagnifierNode` (but that are now created and managed by `FrictionModel`).

**Comment by jbphet** [comment]
@samreid - I've made a number of changes that should address this issue.  Please review, noting the comments above as part of the process.  I've published a dev release and set up a test task for QA, since these changes were substantial.

There is still a lot that could be improved about the code for this sim, but hopefully this is a step in the right direction and will help to support phet-io and a11y.

**Comment by samreid** [comment]
A few minutes skimming the changes and using the simulation did not reveal any problems, but it would take probably 2 hours to do a formal review of all the changes.  @ariel-phet want me to schedule time for that?

**Comment by jbphet** [comment]
My 2 cents is that I don't think it warrants full review.  I feel pretty confident that it's an improvement, and QA is going to test (see https://github.com/phetsims/QA/issues/127), so if @samreid's skim didn't reveal anything major, I think that's enough.

**Comment by ariel-phet** [comment]
Agreed, no need for a formal review.

**Comment by jbphet** [comment]
Cool.  Dev testing is complete with no related issues found.  Closing.
