### ISSUE TITLE
PhET-iO Design

### ISSUE THREAD

**Issue by samreid** [phetsims/friction#75]
From #67 

> Have a PhET-iO design meeting for the simulation to identify what should be customizable/interoperable/data stream. For example, see how-to-design-phet-io-features-for-a-simulation.md

We wanted to get this ready for sonification teams to use right away, but when the time is right, this sim needs a PhET-iO design.

**Comment by samreid** [comment]
After discussing https://github.com/phetsims/inverse-square-law-common/issues/53 we also discussed working on PhET-iO for Friction.  Here are the phet-io meeting notes:

> MK: Same question for friction
Consensus: Same answer.  Start with design meeting.
MK: I volunteer to work on the phet-io side for that, I am also doing the a11y implementation for that.

Assigning to @zepumph to get the ball rolling toward design meeting.

**Comment by zepumph** [comment]
We had a Friction phet-io design meeting today, here is the wishlist/notes:

some use cases to think about:
* hiding the micro view but keeping the thermometer.
* (smart sparrow) as a figure in an etextbook, animating but not pickable
metric on assessment
* save and load


  - [ ] did they drag the book
  - [ ] don't need all the atoms
  - [ ] hide the thermometer 
  - [ ] read the temperature
  - [ ] turn the sim more quantitative? Perhaps a percentage
  - [ ] include range of the amplitudeProperty
  - [ ] rename `amplitudeProperty`
      - vibrationAmplitudeProperty?
  - [ ] amplitudeProperty documentation talks about qualitative model
      "A relative, qualitative value going from 1 (small vibration) to 12 (extreme vibration)"
  - [ ] instrument keyboard drag listener?
  - [ ] know when atoms have broken away (evaporation emitter?)
  - [ ] hide the entire micro view (keep the thermometer)
  - [ ] Instrument book text, so that we can change the name of the books, and make invisible
  - [ ] rename macro books to "topBookNode" "bottomBookNode"
  - [ ] uninstrument bottomBookNode, just instrument the text.
  - [ ] utteranceQueue under general
  - [ ] explore instrumenting the canvas node's atoms

For adding `phetioFeatured` to elements, I'll take my best guess.

**Comment by zepumph** [comment]
Friction is no longer needed, apply appropriate labels.

**Comment by zepumph** [comment]
Pretty much all of this is done. I am not sure how we want to support instrumenting the keyboardDragListener. I feel like potentially adding this to the PhET-iO meeting agenda to see if it is worth moving forward for a publication that is coming up already later this month.

**Comment by zepumph** [comment]
We discussed pursuing this during PhET-iO meeting today. @arouinfar thought with a minor review of the tree, we could get things in a good spot to deploy with PhET-iO.

**Comment by arouinfar** [comment]
I reviewed the sim in Studio and provided feedback in #236, so I think we can close this issue.
