### ISSUE TITLE
Shorter alerts for increasing and decreasing amounts of friction

### ISSUE THREAD

**Issue by terracoda** [phetsims/friction#94]
@zepumph, I have created shorter alerts for both increasing friction:
https://docs.google.com/document/d/1v7GM_dNZs86jcRn2X03D2t7HFDb4dQ1h4ayDGXTu63U/edit#heading=h.gg9a5jcu7gps

And decreasing friction:
https://docs.google.com/document/d/1v7GM_dNZs86jcRn2X03D2t7HFDb4dQ1h4ayDGXTu63U/edit#heading=h.1dgh6cbux3jt

Let me know if you have any questions or concerns.

**Comment by terracoda** [comment]
In the first version I felt too many alerts were firing causing a pile up in the utterance queue.
Let's discuss this further in a new issue once the shorter alerts are implemented.

**Comment by zepumph** [comment]
Above commits add a different system for the increasing alerts. I can pretty easily add in the decreasing alerts, but I think there are some tweaks to make for this approach, and I think it will be easier to just to it once, since the decreasing alerts will be a copied approach.

We still are getting quite a bit more repetition than I would like, I'm going to investigate. I'm also noticing that it is hard to get an alert when you have maxed out the temp but keep on vibrating.

Here is a basic explanation of the system that I wrote:
In order to alert an alert you must meet the following criteria:
* temperature has increased over a threshold from the start of this drag (a new drag starts every time a key is pressed/released, even if there are other keys still down)
* you can't have alerted too recently ( you have to wait .5 seconds right now)

From there, each time you alert another alert, you alert the next "hotter/faster" alert. So each new alert happens when you drag 1 "threshold amount" of temp higher than the last alert's temp. 

I want to play with it more, but potentially this could be an approach that we go with long term. I also like the simplicity in the code. These changes are pushed to master.

**Comment by zepumph** [comment]
I just added the decreasing describer, and the main notes for that are as follows:
I didn't use any threshold, just a timer based on when the temp starts decreasing.

I have it working well save the start (there is no initial alert, but rather the first one is 3 seconds after decreasing (which is when I would want the 2nd alert probably)). So we need to add another alert on first decrease, which I don't yet know I to detect well. I would like to be able to use the drag end function, but that is called every time any key is let go, not just when all keys have let go.

There also isn't yet the final alert when everything is settled again, and perhaps there needs to be a threshold set, because it decreases slightly for a bit at the base of the thermometer, and we probably want to call that "cool" and not decreasing.

**Comment by zepumph** [comment]
With work continuing in #98, I think that this is ready for review by @terracoda when she gets back.

**Comment by zepumph** [comment]
@terracoda as you are reviewing how this sounds, I'm happy to discuss the implementation specifics, but I don't want to write out all the nuance right here on what has been decided on so far.

**Comment by zepumph** [comment]
I agree that the increasing system is a bit buggy, but I'm not quite sure how to manage it. The "very hot" alerts don't show up until you do a single drag long enough. So if you hold down the bottom arrow and move the book left to right, there will eventually be a "very hot" alert, but I think the timing is a bit problem. I think this warrants a conversation when you get back, because it will require some discussion as to how to tweak the algorithm to make this work. 

In the mean time I will try to get you a sonification version by EOD.

**Comment by zepumph** [comment]
Much of the problem has to do with https://github.com/phetsims/friction/issues/98, and the issue of timing/interaction length that we have been discussing for weeks now.

**Comment by terracoda** [comment]
@zepumph, you implemented a shorter version of the warmer alert, "Jiggling more, warmer," instead of "Jiggling more, temperature warmer."

I think this works nicely as we get the word, "temperature" on focus in the first alert.

I like the way the cooling-decreasing alerts are working. I hear fewer of them now, and if i just stop interacting, it is a nice direct decline of both jiggling speed and dropping temperature. It's possible that this is enough to map the direct relationship between the two, even though the alerts are less obvious in the warming-increasing alerts.

**Comment by terracoda** [comment]
@zepumph, I think the shorter alerts sound good. I'll close this issue and more improvements will com in #101.
